# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/PdfFlow/Dockerfile'
#        tags: |
#          $(tag)
    - task: Docker@2
      displayName: 'Login to Container Registry'
      inputs:
       command: login
       containerRegistry: 'sandboxpdf'
     
    - task: Docker@2
      displayName: 'Build and push image'
      inputs:
       Dockerfile: '$(Build.SourcesDirectory)/PdfFlow/Dockerfile'
       command: buildAndPush
       repository: '$(DockerImageName)'