version: '3.8'
    
services:
  web:
    image: pdflow:latest
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "Host=db;Port=5432;Username=pdfuser;Password=pdfuser;Database=pdfdb;"
  
  db:
    env_file:
      - .env
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  postgres_data: